// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mvrtzswgozwvodhlshnm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im12cnR6c3dnb3p3dm9kaGxzaG5tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxMDA1MjcsImV4cCI6MjA1ODY3NjUyN30.u_sY07n2QIdZpSjGP_YvjfcwCvEqWfJoBnMFtGWbmWE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);